name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Compose
      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      # Step 3: Build and Start Services
      - name: Build and Start Services
        run: docker-compose up --build -d

      # Step 4: Run Backend Tests
      - name: Run Backend Tests
        run: docker-compose exec backend npm test

      # Step 5: Run Frontend Tests
      - name: Run Frontend Tests
        run: docker-compose exec frontend npm test -- --passWithNoTests

      # Step 6: Run Cypress Tests
      - name: Run Cypress Tests
        run: docker-compose exec frontend npm run cypress:run

      # Step 7: Tear Down Services
      - name: Tear Down
        run: docker-compose down
