name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      # Step 3: Install frontend dependencies
      - name: Install Dependencies
        run: npm ci

  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      # Step 3: Install backend dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 4: Build and test backend
      - name: Build and Test
        run: |
          npm run build
          npm test -- --passWithNoTests

  jest-tests:
    runs-on: ubuntu-latest
    needs: [frontend-install]

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      # Step 3: Install dependencies
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm ci

      # Step 4: Run Jest tests
      - name: Run Jest Tests
        uses: stefanoeb/jest-action@1.0.4
        with:
          jestArgs: --detectOpenHandles

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [jest-tests, backend-tests]

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      # Step 3: Install all dependencies
      - name: Install All Dependencies
        run: |
          cd frontend && npm ci
          cd ../backend && npm ci

      # Step 4: Start backend and frontend servers
      - name: Start Servers
        run: |
          cd backend && npm start &
          cd ../frontend && npm start &
        env:
          NODE_ENV: test
          REACT_APP_API_URL: http://localhost:3000

      # Step 5: Run Cypress tests
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 180
          working-directory: ./frontend
