name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      # Step 3: Navigate to frontend directory
      - name: Change to Frontend Directory
        working-directory: ./frontend

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 5: Run frontend tests
      - name: Run Tests
        run: npm test -- --passWithNoTests
