name: Docker Image CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Log in to Docker Hub (if needed)
      # Uncomment and configure the following steps if you want to push to Docker Hub
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image and tag with latest and commit SHA
      - name: Build the Docker image
        run: |
          IMAGE_NAME=my-image-name
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          GIT_COMMIT_SHA=$(git rev-parse --short HEAD)
          docker build . --file Dockerfile --tag $IMAGE_NAME:latest --tag $IMAGE_NAME:$GIT_COMMIT_SHA --tag $IMAGE_NAME:$TIMESTAMP

      # (Optional) Push the Docker image to a registry
      # Uncomment and configure the following step if you want to push the image
      # - name: Push Docker image
      #   run: |
      #     docker push $IMAGE_NAME:latest
      #     docker push $IMAGE_NAME:$GIT_COMMIT_SHA
      #     docker push $IMAGE_NAME:$TIMESTAMP
