name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test -- --passWithNoTests

  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm ci

      - name: Build and Test
        run: |
          npm run build
          npm test -- --passWithNoTests

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [frontend-unit-tests, backend-tests]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: |
          cd frontend && npm ci
          cd ../backend && npm ci

      - name: Start Servers
        run: |
          cd backend && npm start &
          cd ../frontend && npm start &
        env:
          NODE_ENV: test
          REACT_APP_API_URL: http://localhost:3000

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 180
          working-directory: ./frontend

  jest-tests:
    runs-on: ubuntu-latest
    needs: [frontend-unit-tests, backend-tests]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm ci

      - name: Run Jest Tests
        uses: stefanoeb/jest-action@1.0.4
        with:
          jestArgs: --detectOpenHandles   
