name: Frontend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Run Jest Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify your Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Verify Jest Config Path
        run: ls -al ./frontend/jest.config.ts # Adjust the path to your jest.config.ts

      - name: Run Jest Tests
        run: npx jest --config ./frontend/jest.config.ts # Adjust the path if needed

      - name: Upload Jest Coverage Report (Optional)
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: jest-coverage-report
          path: coverage/
